## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'arduino'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_arduino become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/jerlfan/pymodaq_plugins_arduino' #to modify
description = 'Plugin allowing to use an arduino board using Telemetrix4Arduino firmware (tested version5.3.3)'

author = 'Jérémie Margueritat'
author-email = 'jeremie.margueritat@univ-lyon1.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.0','telemetrix']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
pid_models = false  # true if plugins contains pid models
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

